<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
type Effect={label:string;value:number;direction:string}; type Option={id:string;label:string;risk:string;attributeWeights?:string[];preview?:Effect[]}
type Challenge={gameId:string;mode:string;instructions:string;targetSequence:number[];safeTiles?:number[];choices?:string[];targetLane?:number;dealerScore?:number;playerScore?:number;requiredScore:number;boardSize:number;isLuckGame:boolean}
type Event={id:string;category:string;title:string;description:string;miniGame:string;options:Option[];outcome?:string;challenge?:Challenge;match?:{matchday:number;rival:string;minute:number;teamGoals:number;rivalGoals:number;stakes:string}}
type Player={name:string;nationality:string;shirtNumber:number;position:string;age:number;overall:number;form:number;energy:number;morale:number;injuryRisk:number;reputation:number;pace:number;shooting:number;passing:number;dribbling:number;defending:number;physical:number;money:number;goals:number;assists:number;appearances:number;nationalAppearances:number;ratingTotal:number}
type Award={name:string;reason:string;reputationGain:number;prizeEur:number}; type Summary={season:number;club:string;league:string;appearances:number;goals:number;assists?:number;minutes?:number;annualSalaryEur?:number;marketValueEur?:number;nationalAppearances?:number;average:number;titles:string[];finalPosition:number;awards?:Award[];role?:string;milestones?:string[]}; type Archive={summary:Summary;events:Event[];timeline?:string[]}
type Career={season:number;currentClub:string;currentLeague:string;currentMatchday:number;seasonComplete:boolean;isRetired:boolean;clubRole?:string;seasonMinutes?:number;objectives?:string[];player:Player;contract?:{annualGrossEur:number;monthlyNetEur:number;role:string};marketProfile?:{estimatedValueEur:number;interestLevel:string;scoutingClubs:string[];summary:string};nationalTeam?:{country:string};activeEvent?:Event;lastResolution?:{result:string;score?:string;detail:string;effects:Effect[]};table:{club:string;played:number;points:number}[];trophies:string[];individualAwards?:Award[];seasonArchives:Archive[];timeline?:string[]}
type World={nationalities:string[];leagues:{name:string}[];clubs:{name:string;league:string}[]}
const api='http://localhost:5098/api',career=ref<Career|null>(null),world=ref<World>({nationalities:[],leagues:[],clubs:[]}),busy=ref(false),error=ref(''),openSeason=ref<number|null>(null),meter=ref(0),direction=ref(1),moves=ref<number[]>([]),pattern=ref(false),gameChoice=ref('')
const profile=ref({name:'',nationality:'México',shirtNumber:10,league:'Liga MX',club:'América',position:'Mediocampista',archetype:'Equilibrado',personality:'Profesional'})
const active=computed(()=>career.value?.activeEvent),challenge=computed(()=>active.value?.challenge),clubs=computed(()=>world.value.clubs.filter(c=>c.league===profile.value.league)),average=computed(()=>career.value?.player.appearances?(career.value.player.ratingTotal/career.value.player.appearances).toFixed(2):'—')
const gameTitle=computed(()=>({shoot:'DISPARO DECISIVO',keeper:'REFLEJOS',lanes:'LECTURA DE JUEGO',memory:'MEMORIA DE CAMPO',mines:'ZONA SEGURA',tictactoe:'TRES EN RAYA',targets:'TIRO A OBJETIVOS',dice:'DADOS',roulette:'RULETA',blackjack:'BLACKJACK'}[challenge.value?.mode??'']??'RETO'))
const gridSize=computed(()=>Math.ceil(Math.sqrt(challenge.value?.boardSize??9)))
function normalize(v:Career):Career{return {...v,table:v.table??[],trophies:v.trophies??[],seasonArchives:v.seasonArchives??[]}}
async function request(path:string,init?:RequestInit){const r=await fetch(api+path,{...init,headers:{'Content-Type':'application/json'}});if(!r.ok)throw new Error((await r.json()).error??'No se pudo conectar al motor');return r.json()}
function db(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('camino-a-la-gloria',1);r.onupgradeneeded=()=>r.result.createObjectStore('state');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function persist(v:Career){try{const d=await db();d.transaction('state','readwrite').objectStore('state').put(v,'career')}catch{localStorage.setItem('camino-career',JSON.stringify(v))}}
async function load(){try{const d=await db();const v=await new Promise<Career|undefined>((resolve,reject)=>{const r=d.transaction('state').objectStore('state').get('career');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});if(v)return v}catch{}const raw=localStorage.getItem('camino-career');return raw?JSON.parse(raw):null}
function save(v:Career){career.value=normalize(v);void persist(career.value)} function syncClub(){profile.value.club=clubs.value[0]?.name??''} function tone(value:number,good=70,bad=45){return value>=good?'good':value<=bad?'bad':'warn'} function riskTone(value:number){return value<=18?'good':value>=42?'bad':'warn'}
function resetGame(){moves.value=[];gameChoice.value='';pattern.value=false} function revealPattern(){pattern.value=true;window.setTimeout(()=>pattern.value=false,1250)} function selectCell(cell:number){const c=challenge.value;if(!c||moves.value.includes(cell)||moves.value.length>=Math.max(3,c.targetSequence.length))return;moves.value=[...moves.value,cell]}
function effectText(e:Effect){return e.label==='Saldo'?`€${e.value.toLocaleString('es-ES')}`:`${e.value>0?'+':''}${e.value}`}
async function create(){busy.value=true;try{save(await request('/career',{method:'POST',body:JSON.stringify(profile.value)}))}catch(e){error.value=e instanceof Error?e.message:'Error'}finally{busy.value=false}}
async function choose(id:string){if(!career.value||busy.value)return;busy.value=true;error.value='';const c=challenge.value;const miniGame=c?{moves:moves.value,choice:gameChoice.value,score:c.mode==='shoot'||c.mode==='keeper'?Math.round(100-Math.abs(50-meter.value)*2):undefined}:undefined;try{save(await request('/career/decision',{method:'POST',body:JSON.stringify({career:career.value,optionId:id,miniGame})}));resetGame();setTimeout(()=>void advance(),850)}catch(e){error.value=e instanceof Error?e.message:'Error'}finally{busy.value=false}}
async function advance(){if(!career.value||career.value.activeEvent||career.value.isRetired||busy.value)return;busy.value=true;try{save(await request(career.value.seasonComplete?'/career/advance-season':'/career/advance',{method:'POST',body:JSON.stringify(career.value)}))}catch(e){error.value=e instanceof Error?e.message:'Error'}finally{busy.value=false;if(career.value&&!career.value.activeEvent&&!career.value.isRetired)setTimeout(()=>void advance(),450)}}
function restart(){career.value=null;localStorage.removeItem('camino-career');void db().then(d=>d.transaction('state','readwrite').objectStore('state').delete('career')).catch(()=>{})}
onMounted(async()=>{setInterval(()=>{meter.value+=direction.value*6;if(meter.value>=100||meter.value<=0)direction.value*=-1},75);try{world.value=await request('/world');profile.value.nationality=world.value.nationalities[0]??profile.value.nationality;profile.value.league=world.value.leagues[0]?.name??profile.value.league;syncClub();const saved=await load();if(saved){save(saved);setTimeout(()=>void advance(),300)}}catch(e){error.value=e instanceof Error?e.message:'Error'}})
</script>

<template><main>
<section v-if="!career" class="onboarding"><p class="eyebrow">CAMINO A LA GLORIA</p><h1>Tu carrera empieza aquí.</h1><p class="lead">Juega una historia de fútbol donde tu nivel, rendimiento, dinero y decisiones abren —o cierran— el siguiente escalón.</p><form class="creator" @submit.prevent="create"><label>Nombre<input v-model="profile.name" required maxlength="28"/></label><label>Nacionalidad<select v-model="profile.nationality"><option v-for="x in world.nationalities" :key="x">{{x}}</option></select></label><label>Número<input v-model.number="profile.shirtNumber" type="number" min="1" max="99"/></label><label>Liga<select v-model="profile.league" @change="syncClub"><option v-for="x in world.leagues" :key="x.name" :value="x.name">{{x.name}}</option></select></label><label>Club<select v-model="profile.club"><option v-for="x in clubs" :key="x.name" :value="x.name">{{x.name}}</option></select></label><label>Posición<select v-model="profile.position"><option>Portero</option><option>Defensa</option><option>Mediocampista</option><option>Extremo</option><option>Delantero</option></select></label><label>Arquetipo<select v-model="profile.archetype"><option>Equilibrado</option><option>Talento</option><option>Incansable</option><option>Líder</option></select></label><label>Personalidad<select v-model="profile.personality"><option>Profesional</option><option>Ambicioso</option><option>Sereno</option><option>Carismático</option></select></label><button :disabled="busy">{{busy?'Preparando...':'Empezar carrera'}}</button></form><p v-if="error" class="error">{{error}}</p></section>
<template v-else><header class="topbar"><div><p class="eyebrow">TEMPORADA {{career.season}} · JORNADA {{career.currentMatchday}}</p><h2>{{career.currentClub}}</h2><span>{{career.currentLeague}} · Saldo €{{career.player.money.toLocaleString('es-ES',{maximumFractionDigits:0})}}</span></div><button class="quiet" @click="restart">Nueva carrera</button></header>
<section class="player-card"><div class="overall" :class="tone(career.player.overall,75,58)"><strong>{{career.player.overall}}</strong><span>MEDIA</span></div><div><p class="eyebrow">{{career.player.nationality}} · #{{career.player.shirtNumber}} · {{career.player.position}} · {{career.player.age}} AÑOS</p><h1>{{career.player.name}}</h1><p v-if="career.contract">{{career.contract.role}} · €{{career.contract.annualGrossEur.toLocaleString('es-ES')}} brutos/año · €{{career.contract.monthlyNetEur.toLocaleString('es-ES')}} netos/mes</p></div><div class="metrics"><span :class="tone(career.player.form)">Forma <b>{{career.player.form}}</b><small>{{career.player.form>=70?'EN RACHA':career.player.form<=45?'BAJA FORMA':'ESTABLE'}}</small></span><span :class="tone(career.player.energy)">Energía <b>{{career.player.energy}}</b><small>{{career.player.energy>=70?'LISTO':career.player.energy<=45?'CANSADO':'GESTIONA'}}</small></span><span :class="tone(career.player.morale)">Moral <b>{{career.player.morale}}</b><small>{{career.player.morale>=70?'CONFIADO':career.player.morale<=45?'TOCADO':'NEUTRAL'}}</small></span><span :class="riskTone(career.player.injuryRisk)">Riesgo lesión <b>{{career.player.injuryRisk}}</b><small>{{career.player.injuryRisk<=18?'BAJO':career.player.injuryRisk>=42?'ALTO':'VIGILA'}}</small></span></div></section>
<section class="attribute-card"><p class="eyebrow">PERFIL FIFA · VALOR €{{career.marketProfile?.estimatedValueEur?.toLocaleString('es-ES',{maximumFractionDigits:0})??'—'}} · {{career.marketProfile?.interestLevel??'Construyendo reputación'}}</p><div class="attribute-grid"><span :class="tone(career.player.pace)">PAC<b>{{career.player.pace}}</b></span><span :class="tone(career.player.shooting)">SHO<b>{{career.player.shooting}}</b></span><span :class="tone(career.player.passing)">PAS<b>{{career.player.passing}}</b></span><span :class="tone(career.player.dribbling)">DRI<b>{{career.player.dribbling}}</b></span><span :class="tone(career.player.defending)">DEF<b>{{career.player.defending}}</b></span><span :class="tone(career.player.physical)">PHY<b>{{career.player.physical}}</b></span><span :class="tone(career.player.reputation,55,22)">FAMA<b>{{career.player.reputation}}</b></span></div><p v-if="career.marketProfile" class="market-copy">{{career.marketProfile.summary}} <b v-if="career.marketProfile.scoutingClubs.length">Te observan: {{career.marketProfile.scoutingClubs.join(' · ')}}</b></p></section>
<section class="career-pulse"><article><p class="eyebrow">ROL EN EL CLUB</p><strong :class="career.clubRole==='Titular'?'good':career.clubRole==='Fuera de convocatoria'?'bad':'warn'">{{career.clubRole??'Cantera'}}</strong><small>{{career.seasonMinutes??0}} minutos esta temporada</small></article><article><p class="eyebrow">SEÑALES DE TU CARRERA</p><p v-for="hint in career.objectives??['El calendario te dará nuevas señales.']" :key="hint">{{hint}}</p></article></section>
<section class="grid"><article class="event-card"><p class="eyebrow">{{active?.category??(busy?'SIMULANDO':'CALENDARIO')}}</p><h2>{{active?.title??'La temporada sigue fluyendo'}}</h2><p>{{active?.description??'El motor avanza automáticamente hacia la siguiente situación.'}}</p><div v-if="active?.match" class="match-context"><span>JORNADA {{active.match.matchday}} · MIN {{active.match.minute}}</span><strong>{{career.currentClub}} {{active.match.teamGoals}} — {{active.match.rivalGoals}} {{active.match.rival}}</strong><small>{{active.match.stakes}}</small></div>
<div v-if="challenge" class="mini-arena" :class="'arena-'+challenge.mode"><div class="arena-heading"><div><p class="eyebrow">{{gameTitle}}</p><b>{{challenge.instructions}}</b></div><span v-if="challenge.mode==='shoot'||challenge.mode==='keeper'">PRECISIÓN {{Math.round(100-Math.abs(50-meter)*2)}}%</span></div>
<template v-if="challenge.mode==='shoot'||challenge.mode==='keeper'"><div class="goal-grid"><button v-for="(zone,index) in ['Izquierda','Centro','Derecha']" :key="zone" :class="{selected:moves[0]===index}" @click="moves=[index]"><i></i>{{zone}}</button></div><div class="precision-track"><i :style="{left:meter+'%'}"></i><b></b></div><small>Elige una zona y detén el marcador cerca del centro al resolver.</small></template>
<template v-else-if="challenge.isLuckGame"><div v-if="challenge.mode==='blackjack'" class="cards"><span>Tu mano <b>{{challenge.playerScore}}</b></span><span>Crupier <b>?</b></span></div><div class="luck-choices"><button v-for="choice in challenge.choices" :key="choice" :class="{selected:gameChoice===choice}" @click="gameChoice=choice">{{choice}}</button></div><small v-if="challenge.mode==='roulette'">Verde multiplica el premio, pero es el resultado menos probable.</small><small v-else-if="challenge.mode==='blackjack'">Acércate a 21 sin pasarte. Doblar aumenta también el riesgo.</small></template>
<template v-else><div class="arena-toolbar"><button class="quiet" @click="revealPattern">{{pattern?'Ocultar patrón':'Ver patrón'}}</button><strong v-if="pattern">{{challenge.targetSequence.map(x=>x+1).join(' → ')}}</strong><span v-else>{{moves.length}} / {{challenge.mode==='mines'||challenge.mode==='tictactoe'?3:challenge.targetSequence.length}} marcados</span></div><div class="play-grid" :style="{gridTemplateColumns:'repeat('+gridSize+',1fr)'}"><button v-for="cell in challenge.boardSize" :key="cell" :class="{selected:moves.includes(cell-1),mine:challenge.mode==='mines'&&moves.includes(cell-1)}" @click="selectCell(cell-1)">{{challenge.mode==='tictactoe'&&moves.includes(cell-1)?'X':cell}}</button></div><small v-if="challenge.mode==='mines'">Encuentra tres casillas seguras. No podrás corregir un toque.</small><small v-else-if="challenge.mode==='tictactoe'">Marca una línea de tres X para superar el reto.</small><small v-else>Memoriza la secuencia, ocúltala y repítela con los cuadros.</small></template></div>
<div v-if="active" class="minigame">{{active.miniGame}} · elige una acción</div><div class="choices" v-if="active"><button v-for="o in active.options" :key="o.id" :disabled="busy" @click="choose(o.id)"><b>{{o.label}}</b><small>Riesgo: {{o.risk}} <template v-if="o.attributeWeights?.length">· Usa: {{o.attributeWeights.join(' / ')}}</template></small><span v-for="e in o.preview" :key="e.label" class="preview">{{e.label}} +{{e.value}}</span></button></div><p v-else class="loading">{{busy?'Simulando calendario...':'Preparando el siguiente momento...'}}</p><p v-if="error" class="error">{{error}}</p></article>
<article class="stats-card"><p class="eyebrow">CARRERA</p><div class="stat-row"><span>PJ</span><b>{{career.player.appearances}}</b></div><div class="stat-row"><span>Goles</span><b>{{career.player.goals}}</b></div><div class="stat-row"><span>Asistencias</span><b>{{career.player.assists}}</b></div><div class="stat-row"><span>Media</span><b>{{average}}</b></div><div class="stat-row"><span>Títulos</span><b>{{career.trophies.length}}</b></div><p v-if="career.nationalTeam" class="eyebrow selection-label">SELECCIÓN · {{career.nationalTeam.country}}</p></article><article class="table-card"><p class="eyebrow">{{career.currentLeague}}</p><ol><li v-for="(x,i) in career.table" :key="x.club"><span>{{i+1}}. {{x.club}} <small>{{x.played}} PJ</small></span><b>{{x.points}} pts</b></li></ol></article></section>
<section v-if="career.lastResolution" class="resolution"><p class="eyebrow">RESULTADO DE TU DECISIÓN</p><h3>{{career.lastResolution.result}} <small v-if="career.lastResolution.score">· {{career.lastResolution.score}}</small></h3><p>{{career.lastResolution.detail}}</p><span v-for="x in career.lastResolution.effects" :key="x.label" :class="x.direction">{{x.label}} {{effectText(x)}}</span></section>
<section class="archives"><p class="eyebrow">HISTORIAL DE CARRERA · {{career.individualAwards?.length??0}} PREMIOS INDIVIDUALES</p><article v-for="a in career.seasonArchives.slice().reverse()" :key="a.summary.season" class="season"><button @click="openSeason=openSeason===a.summary.season?null:a.summary.season"><b>{{a.summary.season}} · {{a.summary.club}}</b><span>{{a.summary.appearances}} PJ · {{a.summary.goals}} G · {{a.summary.average.toFixed(2)}} media · {{a.summary.titles.length}} títulos</span></button><div v-if="openSeason===a.summary.season" class="season-detail"><div class="season-numbers"><span><b>{{a.summary.assists??0}}</b> asist.</span><span><b>{{a.summary.minutes??0}}</b> min.</span><span><b>{{a.summary.nationalAppearances??0}}</b> selección</span><span><b>{{a.summary.role??'—'}}</b> rol</span></div><p>Posición final: {{a.summary.finalPosition}}º · {{a.summary.league}} · Valor €{{a.summary.marketValueEur?.toLocaleString('es-ES')??'—'}}</p><p>{{a.summary.titles.join(' · ')||'Sin títulos esta temporada'}}</p><p v-for="award in a.summary.awards" :key="award.name" class="award">🏆 {{award.name}} · {{award.reason}} · +{{award.reputationGain}} fama <template v-if="award.prizeEur">· €{{award.prizeEur.toLocaleString('es-ES')}}</template></p><div v-if="a.summary.milestones?.length" class="milestones"><b>Hitos</b><p v-for="m in a.summary.milestones" :key="m">{{m.replace(a.summary.season+': ','')}}</p></div><div class="season-log"><b>Lo que ocurrió</b><p v-for="e in a.events" :key="e.id">{{e.outcome||e.title}}</p></div></div></article></section></template>
</main></template>
