<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
type Option = { id: string; label: string; risk: string }
type Effect = { label: string; value: number; direction: string }
type Resolution = { headline: string; result: string; score?: string; detail: string; effects: Effect[] }
type Challenge = { gameId:string; instructions:string; targetSequence:number[]; requiredScore:number; boardSize:number; isLuckGame:boolean }
type Event = { id: string; category: string; title: string; description: string; miniGame: string; options: Option[]; outcome?:string; challenge?:Challenge; match?: { matchday:number; rival:string; minute:number; teamGoals:number; rivalGoals:number; stakes:string; isDecisive:boolean }; requiredSelections?:number }
type Ledger = { id:string; season:number; month:string; category:string; description:string; amountEur:number; balanceAfter:number }
type Archive = { summary:{season:number;club:string;league:string;appearances:number;goals:number;average:number;titles:string[];finalPosition:number}; events:Event[]; timeline:string[]; ledger:Ledger[] }
type Player = { name:string; nationality:string; shirtNumber:number; position:string; age:number; overall:number; form:number; energy:number; morale:number; injuryRisk:number; money:number; goals:number; assists:number; appearances:number; ratingTotal:number }
type Contract = { annualGrossEur:number; monthlyNetEur:number; role:string; club:string }
type Career = { season:number;currentClub:string;currentLeague:string;currentMatchday:number;seasonComplete:boolean;isRetired:boolean;player:Player;contract?:Contract;activeEvent?:Event;lastResolution?:Resolution;table:{club:string;played:number;points:number}[];trophies:string[];timeline:string[];ledger:Ledger[];seasonArchives:Archive[] }
type Club = { name:string; league:string }; type World = { nationalities:string[]; leagues:{name:string;region:string}[]; clubs:Club[] }
const api='http://localhost:5098/api'; const career=ref<Career|null>(null); const world=ref<World>({nationalities:[],leagues:[],clubs:[]}); const busy=ref(false); const error=ref(''); const openSeason=ref<number|null>(null)
const profile=ref({name:'',nationality:'México',shirtNumber:10,league:'Liga MX',club:'América',position:'Mediocampista',archetype:'Equilibrado',personality:'Profesional'}); const meter=ref(0); const meterDirection=ref(1); const gameMoves=ref<number[]>([]); const showPattern=ref(false)
const clubsForLeague=computed(()=>world.value.clubs.filter(x=>x.league===profile.value.league)); const average=computed(()=>!career.value?.player.appearances?'—':(career.value.player.ratingTotal/career.value.player.appearances).toFixed(2)); const active=computed(()=>career.value?.activeEvent); const isPreseason=computed(()=>active.value?.category==='Pretemporada'); const selected=ref<string>('')
function db(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('camino-a-la-gloria',1);r.onupgradeneeded=()=>r.result.createObjectStore('state');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function loadState(){try{const d=await db();const value=await new Promise<Career|undefined>((resolve,reject)=>{const r=d.transaction('state').objectStore('state').get('career');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});if(value)return normalize(value)}catch{}const legacy=localStorage.getItem('camino-career');return legacy?normalize(JSON.parse(legacy)):null}
async function persist(value:Career){try{const d=await db();d.transaction('state','readwrite').objectStore('state').put(value,'career')}catch{localStorage.setItem('camino-career',JSON.stringify(value))}}
function normalize(value:Career):Career{return {...value,trophies:value.trophies??[],timeline:value.timeline??[],table:value.table??[],ledger:value.ledger??[],seasonArchives:value.seasonArchives??[]}}
function save(value:Career){career.value=normalize(value);void persist(career.value)}
async function request(path:string,init:RequestInit){const r=await fetch(api+path,{...init,headers:{'Content-Type':'application/json'}});if(!r.ok)throw new Error((await r.json()).error??'No se pudo conectar al motor.');return r.json()}
function message(e:unknown){return e instanceof Error?e.message:'Error inesperado'}
function syncClub(){profile.value.club=clubsForLeague.value[0]?.name??''}
async function createCareer(){busy.value=true;try{save(await request('/career',{method:'POST',body:JSON.stringify(profile.value)}))}catch(e){error.value=message(e)}finally{busy.value=false}}
function tapGameCell(cell:number){if(!active.value?.challenge||busy.value)return;gameMoves.value=[...gameMoves.value,cell]}
function revealPattern(){showPattern.value=true;window.setTimeout(()=>showPattern.value=false,1400)}
async function choose(id:string){if(!career.value||busy.value)return;busy.value=true;error.value='';const c=active.value?.challenge;const miniGame=c?{moves:gameMoves.value,score:c.boardSize===100?Math.round(100-Math.abs(50-meter.value)*2):undefined}:undefined;try{save(await request('/career/decision',{method:'POST',body:JSON.stringify({career:career.value,optionId:id,miniGame})}));selected.value='';gameMoves.value=[];showPattern.value=false;window.setTimeout(()=>void autoAdvance(),850)}catch(e){error.value=message(e)}finally{busy.value=false}}
async function autoAdvance(){if(!career.value||career.value.activeEvent||career.value.isRetired||busy.value)return;busy.value=true;try{const path=career.value.seasonComplete?'/career/advance-season':'/career/advance';save(await request(path,{method:'POST',body:JSON.stringify(career.value)}))}catch(e){error.value=message(e)}finally{busy.value=false;if(career.value&&!career.value.activeEvent&&!career.value.isRetired)window.setTimeout(()=>void autoAdvance(),450)}}
function restart(){career.value=null;localStorage.removeItem('camino-career');void db().then(d=>d.transaction('state','readwrite').objectStore('state').delete('career')).catch(()=>{})}
onMounted(async()=>{window.setInterval(()=>{meter.value+=meterDirection.value*7;if(meter.value>=100||meter.value<=0)meterDirection.value*=-1},80);try{world.value=await request('/world',{method:'GET'});profile.value.nationality=world.value.nationalities[0]??profile.value.nationality;profile.value.league=world.value.leagues[0]?.name??profile.value.league;syncClub();career.value=await loadState();if(career.value)window.setTimeout(()=>void autoAdvance(),300)}catch(e){error.value=message(e)}})
</script>
<template><main>
<section v-if="!career" class="onboarding"><p class="eyebrow">CAMINO A LA GLORIA</p><h1>Tu carrera empieza aquí.</h1><p class="lead">Contrato anual, dinero ganado y decisiones que dejan huella.</p><form class="creator" @submit.prevent="createCareer"><label>Nombre<input v-model="profile.name" required maxlength="28"/></label><label>Nacionalidad<select v-model="profile.nationality"><option v-for="x in world.nationalities">{{x}}</option></select></label><label>Número<input v-model.number="profile.shirtNumber" type="number" min="1" max="99"/></label><label>Liga<select v-model="profile.league" @change="syncClub"><option v-for="x in world.leagues" :value="x.name">{{x.name}}</option></select></label><label>Club<select v-model="profile.club"><option v-for="x in clubsForLeague" :value="x.name">{{x.name}}</option></select></label><label>Posición<select v-model="profile.position"><option>Portero</option><option>Defensa</option><option>Mediocampista</option><option>Extremo</option><option>Delantero</option></select></label><label>Arquetipo<select v-model="profile.archetype"><option>Equilibrado</option><option>Talento</option><option>Incansable</option><option>Líder</option></select></label><label>Personalidad<select v-model="profile.personality"><option>Profesional</option><option>Ambicioso</option><option>Sereno</option><option>Carismático</option></select></label><button :disabled="busy">{{busy?'Preparando...':'Empezar carrera'}}</button></form></section>
<template v-else><header class="topbar"><div><p class="eyebrow">TEMPORADA {{career.season}} · JORNADA {{career.currentMatchday}}</p><h2>{{career.currentClub}}</h2><span>{{career.currentLeague}} · Saldo €{{career.player.money.toLocaleString('es-ES',{maximumFractionDigits:0})}}</span></div><button class="quiet" @click="restart">Nueva carrera</button></header>
<section class="player-card"><div class="overall"><strong>{{career.player.overall}}</strong><span>MEDIA</span></div><div><p class="eyebrow">{{career.player.nationality}} · #{{career.player.shirtNumber}} · {{career.player.position}} · {{career.player.age}} AÑOS</p><h1>{{career.player.name}}</h1><p v-if="career.contract">{{career.contract.role}} · €{{career.contract.annualGrossEur.toLocaleString('es-ES')}} brutos/año · €{{career.contract.monthlyNetEur.toLocaleString('es-ES')}} netos/mes</p></div><div class="metrics"><span>Forma <b>{{career.player.form}}</b></span><span>Energía <b>{{career.player.energy}}</b></span><span>Moral <b>{{career.player.morale}}</b></span><span>Riesgo lesión <b>{{career.player.injuryRisk}}</b></span></div></section>
<section class="grid"><article class="event-card"><p class="eyebrow">{{active?.category??(busy?'SIMULANDO':'CALENDARIO')}}</p><h2>{{active?.title??'La temporada sigue fluyendo'}}</h2><p>{{active?.description??'El motor avanza automáticamente hacia la siguiente situación.'}}</p><div v-if="active?.match" class="match-context"><span>JORNADA {{active.match.matchday}} · MIN {{active.match.minute}}</span><strong>{{career.currentClub}} {{active.match.teamGoals}} — {{active.match.rivalGoals}} {{active.match.rival}}</strong><small>{{active.match.stakes}}</small></div><div v-if="active?.challenge" class="challenge"><b>{{active.challenge.instructions}}</b><div v-if="active.challenge.boardSize===100" class="timing-game"><span>PRECISIÓN: {{Math.round(100-Math.abs(50-meter)*2)}}% · necesitas {{active.challenge.requiredScore}}%</span><div class="meter"><i :style="{left:meter+'%'}"></i><b></b></div></div><div v-else-if="active.challenge.isLuckGame" class="choices"><button :class="{selected:gameMoves[0]===0}" @click="gameMoves=[0]">Bajo (1–3)</button><button :class="{selected:gameMoves[0]===1}" @click="gameMoves=[1]">Alto (4–6)</button></div><template v-else><button class="quiet" @click="revealPattern">{{showPattern?'Patrón: '+active.challenge.targetSequence.join(' → '):'Ver patrón'}}</button><p>Tu secuencia: {{gameMoves.join(' → ')||'—'}}</p><div class="game-grid" :style="{gridTemplateColumns:'repeat('+Math.ceil(Math.sqrt(active.challenge.boardSize))+',1fr)'}"><button v-for="cell in active.challenge.boardSize" :key="cell" :disabled="busy" @click="tapGameCell(cell-1)">{{cell}}</button></div></template></div><div v-else-if="active?.match?.isDecisive" class="timing-game"><span>PRECISIÓN: {{Math.round(100-Math.abs(50-meter)*2)}}%</span><div class="meter"><i :style="{left:meter+'%'}"></i><b></b></div></div><div v-if="active" class="minigame">{{active.miniGame}} · {{active.challenge?'completa el reto y elige la acción':active.category==='Contrato'?'elige tu próximo club':active.category==='Pretemporada'?'elige tu rutina':'elige una acción'}}</div><div class="choices" v-if="active"><button v-for="o in active.options" :key="o.id" :disabled="busy" @click="choose(o.id)">{{o.label}}<small>Riesgo: {{o.risk}}</small></button></div><p v-else class="loading">{{busy?'Simulando calendario...':'Preparando el siguiente momento...'}}</p><p v-if="error" class="error">{{error}}</p></article>
<article class="stats-card"><p class="eyebrow">CARRERA</p><div class="stat-row"><span>PJ</span><b>{{career.player.appearances}}</b></div><div class="stat-row"><span>Goles</span><b>{{career.player.goals}}</b></div><div class="stat-row"><span>Asistencias</span><b>{{career.player.assists}}</b></div><div class="stat-row"><span>Media</span><b>{{average}}</b></div><div class="stat-row"><span>Títulos</span><b>{{career.trophies.length}}</b></div></article>
<article class="table-card"><p class="eyebrow">{{career.currentLeague}}</p><ol><li v-for="(x,i) in career.table" :key="x.club"><span>{{i+1}}. {{x.club}} <small>{{x.played}} PJ</small></span><b>{{x.points}} pts</b></li></ol></article></section>
<section v-if="career.lastResolution" class="resolution"><p class="eyebrow">RESULTADO DE TU DECISIÓN</p><h3>{{career.lastResolution.result}} <small v-if="career.lastResolution.score">· {{career.lastResolution.score}}</small></h3><p>{{career.lastResolution.detail}}</p><span v-for="x in career.lastResolution.effects" :class="x.direction">{{x.label}} {{x.value>0?'+':''}}{{x.value}}</span></section>
<section class="archives"><p class="eyebrow">TEMPORADAS</p><article v-for="a in career.seasonArchives.slice().reverse()" :key="a.summary.season" class="season"><button @click="openSeason=openSeason===a.summary.season?null:a.summary.season"><b>{{a.summary.season}} · {{a.summary.club}}</b><span>{{a.summary.appearances}} PJ · {{a.summary.goals}} G · {{a.summary.average.toFixed(2)}} media · {{a.summary.titles.length}} títulos</span></button><div v-if="openSeason===a.summary.season"><p>Posición final: {{a.summary.finalPosition}}º · {{a.summary.league}}</p><p>{{a.summary.titles.join(' · ')||'Sin títulos'}}</p><p v-for="e in a.events" :key="e.id">{{e.outcome||e.title}}</p><p v-for="l in a.ledger" :key="l.id">{{l.category}}: {{l.amountEur>=0?'+':''}}€{{l.amountEur.toLocaleString('es-ES')}} · {{l.description}}</p></div></article></section>
</template></main></template>
